# Generated by Django 2.2.5 on 2020-03-03 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='circket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=40)),
                ('team2', models.CharField(max_length=40)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('team1_score', models.CharField(max_length=30)),
                ('team2_score', models.CharField(max_length=30)),
                ('result', models.CharField(max_length=30)),
            ],
        ),
    ]
